apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer
  labels:
    app: customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "customer"
        dapr.io/app-port: "5002"
    spec:
      containers:
      - name: customer
        image: superheatedboy/customer:latest
        ports:
        - containerPort: 5002
        imagePullPolicy: Always